apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root 
  finalizers:
  - resources-finalizer.argocd.argoproj.io 
spec:
  destination:
    server: http://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps/
    repoURL: https://github.com/flatnine/argotest.git
    targetRevision: HEAD 
  syncPolicy: 
    automated:
      prune: true 
      selfHeal: true

